"""Milestone 1 reports: preprocessing checks and data summary (Markdown + figures)."""
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from PIL import Image  # noqa: E402


def image_grid(paths, ncol=8, tile=128, gap=2):
    n = len(paths)
    nrow = max(1, -(-n // ncol))
    grid = Image.new("RGB", (ncol * (tile + gap) - gap, nrow * (tile + gap) - gap), (255, 255, 255))
    for k, p in enumerate(paths):
        with Image.open(p) as im:
            grid.paste(im.convert("RGB").resize((tile, tile)), ((k % ncol) * (tile + gap), (k // ncol) * (tile + gap)))
    return grid


def _header(prov):
    return (f"<!-- generated by scripts/prepare_data.py; do not edit -->\n"
            f"Provenance: git `{prov['git_hash']}`, config `{prov['config_path']}`, seed {prov['seed']}, "
            f"dataset manifest `{prov['dataset_manifest_hash'][:16]}`, created {prov['created_utc']}\n")


def _hist(ax, x, bins, title, xlabel, logy=False):
    ax.hist(x, bins=bins, color="#4472c4")
    ax.set(title=title, xlabel=xlabel, ylabel="images")
    if logy:
        ax.set_yscale("log")


def preprocessing_report(meta, derived_root, out_dir, prov, gate_frac, gate_share, determinism, seed=0, gate_action="stop"):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    derived_root = Path(derived_root)
    rng = np.random.default_rng(seed)
    n = len(meta)
    padded = meta.pad_fraction > 0
    big_pad = meta.pad_fraction > gate_frac
    below = meta.margin_used < 1.5 - 1e-9

    fig, axes = plt.subplots(2, 2, figsize=(11, 8))
    _hist(axes[0, 0], meta.loc[padded, "pad_fraction"], 40, f"pad_fraction (padded images only, n={padded.sum()})", "pad_fraction")
    _hist(axes[0, 1], meta.margin_used, np.linspace(1.0, 1.52, 53), "margin_used = s / m", "s / m", logy=True)
    axes[1, 0].scatter(meta.orig_W, meta.orig_H, s=2, alpha=0.3)
    axes[1, 0].set(xscale="log", yscale="log", title="original size", xlabel="W (px)", ylabel="H (px)")
    _hist(axes[1, 1], np.log10(np.minimum(meta.orig_W, meta.orig_H)), 50, "original short side", "log10(short side px)")
    fig.tight_layout()
    fig.savefig(out_dir / "preprocessing_hists.png", dpi=120)
    plt.close(fig)

    tile = lambda ids, var="bbox15_128": [derived_root / var / f"{i}.png" for i in ids]  # noqa: E731
    grids = {
        "grid_random64.png": tile(meta.id.to_numpy()[rng.choice(n, 64, replace=False)]),
        "grid_most_padded32.png": tile(meta.sort_values(["pad_fraction", "id"], ascending=[False, True]).id[:32]),
        "grid_smallest_margin32.png": tile(meta.sort_values(["margin_used", "id"]).id[:32]),
    }
    pair_ids = meta.id.to_numpy()[rng.choice(n, 16, replace=False)]
    grids["grid_bbox15_vs_fullcc16.png"] = [p for i in pair_ids for p in (tile([i])[0], tile([i], "full_cc_128")[0])]
    for name, paths in grids.items():
        image_grid(paths).save(out_dir / name)

    q = meta.pad_fraction.quantile([0.5, 0.9, 0.99, 1.0]).round(4).to_dict()
    gate_ok = big_pad.mean() <= gate_share
    lines = [
        "# Preprocessing report (Milestone 1)", "", _header(prov), "",
        "Main variant `bbox15` (docs/PLAN.md A2b), ablation `full_cc`. Figures are local only (PNG is git-ignored).", "",
        "## Statistics", "",
        "| quantity | value |", "|---|---|",
        f"| images | {n} |",
        f"| needing any padding | {padded.sum()} ({padded.mean():.2%}) |",
        f"| pad_fraction > {gate_frac} | {big_pad.sum()} ({big_pad.mean():.2%}) |",
        f"| pad_fraction quantiles (all images) 50/90/99/100% | {q[0.5]} / {q[0.9]} / {q[0.99]} / {q[1.0]} |",
        f"| margin_used < 1.5 (context reduced) | {below.sum()} ({below.mean():.2%}) |",
        f"| margin_used min / median | {meta.margin_used.min():.3f} / {meta.margin_used.median():.3f} |",
        f"| greyscale (converted to RGB) | {int(meta.was_grayscale.sum())} |",
        f"| bboxes clipped to image | {int(meta.bbox_clipped.sum())} |",
        f"| original W: min / median / max | {meta.orig_W.min()} / {int(meta.orig_W.median())} / {meta.orig_W.max()} |",
        f"| original H: min / median / max | {meta.orig_H.min()} / {int(meta.orig_H.median())} / {meta.orig_H.max()} |",
        f"| original short side < 128 / < 256 | {(np.minimum(meta.orig_W, meta.orig_H) < 128).sum()} / {(np.minimum(meta.orig_W, meta.orig_H) < 256).sum()} |",
        f"| crop side < 128 / < 256 px (upsampled) | {(meta.side < 128).sum()} / {(meta.side < 256).sum()} |",
        "",
        f"**Pad gate** (> {gate_share:.0%} of images with pad_fraction > {gate_frac}; action: {gate_action}): "
        f"{'PASS' if gate_ok else ('FAIL - STOP' if gate_action == 'stop' else 'EXCEEDED - accepted')} ({big_pad.mean():.2%}).", "",
        *([] if gate_ok or gate_action == "stop" else [
            "Decision (30 Sep 2026): keep the A2b spec (whole car always inside the square, constant letterbox padding). "
            "Padding is geometrically unavoidable here: in most images the car's longer side exceeds the image's short "
            "side. The gate is kept as a report; the hard check is that no image is padded where the window fits.", ""]),
        f"**Determinism**: {determinism}", "",
        "## Unit tests (tests/test_crops.py)", "",
        "- 1-indexed inclusive devkit bbox -> 0-indexed half-open, checked pixel-exactly on a synthetic image.",
        "- Car aspect ratio preserved within 1% (sub-pixel measurement on synthetic images, incl. padded cases).",
        "- Transformed bbox lies fully inside the crop (pixel test + 5000 random geometries).",
        "- Output always square; shift (not shrink) at borders; padding only when s > image side, split equally, constant colour.",
        "- 128 and 256 are each resized directly from the square; PNG encoding byte-deterministic.", "",
        "## Figures", "",
        "![histograms](preprocessing_hists.png)", "",
        "64 random bbox15 crops: ![](grid_random64.png)", "",
        "32 most padded: ![](grid_most_padded32.png)", "",
        "32 smallest margin_used: ![](grid_smallest_margin32.png)", "",
        "16 pairs (bbox15 | full_cc): ![](grid_bbox15_vs_fullcc16.png)", "",
        "## Most padded images", "",
        meta.sort_values("pad_fraction", ascending=False).head(10)[
            ["id", "orig_W", "orig_H", "side", "pad_fraction", "margin_used"]].to_markdown(index=False), "",
    ]
    (out_dir / "preprocessing.md").write_text("\n".join(lines))
    return gate_ok, big_pad.mean()


def data_summary_report(meta, hierarchy, dups, out_dir, prov, nn_summary=None, dup_cfg=None):
    out_dir = Path(out_dir)
    kc = hierarchy.groupby(["make_id", "make"]).fine_id.count().rename("K_c")
    per_make = hierarchy.groupby("make_id").agg(make=("make", "first"), K_c=("fine_id", "count")).join(
        meta.pivot_table(index="make_id", columns="split", values="id", aggfunc="count").fillna(0).astype(int))
    per_make = per_make[["make", "K_c", "train", "val", "test"]].sort_values(["K_c", "make"], ascending=[False, True])
    per_fine = meta.pivot_table(index="fine_id", columns="split", values="id", aggfunc="count").fillna(0).astype(int)
    per_fine = hierarchy.set_index("fine_id")[["class_name", "make", "model", "year"]].join(per_fine)
    per_make.to_csv(out_dir / "images_per_make.csv")
    per_fine.to_csv(out_dir / "images_per_fine_class.csv")

    kc_vals = kc.to_numpy()
    fig, axes = plt.subplots(1, 3, figsize=(17, 4.5))
    axes[0].hist(kc_vals, bins=np.arange(0.5, kc_vals.max() + 1.5), color="#4472c4", edgecolor="w")
    axes[0].set(title="K_c: fine classes per make (49 makes)", xlabel="K_c", ylabel="makes")
    pm = per_make.sort_values("train", ascending=False)
    axes[1].bar(range(len(pm)), pm.train + pm.val, label="train+val")
    axes[1].bar(range(len(pm)), pm.test, bottom=pm.train + pm.val, label="test")
    axes[1].set_xticks(range(len(pm)), pm.make, rotation=90, fontsize=6)
    axes[1].set(title="images per make", ylabel="images")
    axes[1].legend()
    axes[2].hist([per_fine.train + per_fine.val, per_fine.test], bins=20, label=["official train", "test"])
    axes[2].set(title="images per fine class", xlabel="images", ylabel="classes")
    axes[2].legend()
    fig.tight_layout()
    fig.savefig(out_dir / "data_summary.png", dpi=120)
    plt.close(fig)

    split_counts = meta.split.value_counts().to_dict()
    half = meta.test_half.value_counts().to_dict()
    mm = hierarchy.groupby("make_model").fine_id.count()
    dup_ids = set(dups.test_id) | set(dups.train_id) if len(dups) else set()
    lines = [
        "# Data summary (Milestone 1)", "", _header(prov), "",
        f"- Images: {len(meta)}; splits: {json.dumps(split_counts)}; test halves: {json.dumps(half)}",
        f"- Makes: {hierarchy.make.nunique()}; fine classes (make-model-year): {len(hierarchy)}; "
        f"make-model classes (years merged): {len(mm)} ({(mm > 1).sum()} merge >1 year)",
        f"- K_c: min {kc_vals.min()}, median {np.median(kc_vals):g}, max {kc_vals.max()}; "
        f"makes with K_c = 1 ({(kc_vals == 1).sum()}): {', '.join(kc[kc == 1].index.get_level_values(1))}",
        f"- Fine class size (official train): {int((per_fine.train + per_fine.val).min())}-{int((per_fine.train + per_fine.val).max())}; "
        f"test: {per_fine.test.min()}-{per_fine.test.max()}; val per class: {per_fine.val.min()}-{per_fine.val.max()}",
        "", "![](data_summary.png)", "",
        "## Near-duplicate audit (official train vs test, raw images)", "",
    ]
    if dup_cfg:
        lines += [f"Criteria: pHash Hamming <= {dup_cfg['phash_max_hamming']} (64-bit) OR SSCD disc_mixup cosine >= "
                  f"{dup_cfg['sscd_threshold']} (small_288 transform). Pairs are marked in metadata, never removed.", ""]
    lines += [
        f"- Candidate pairs: {len(dups)} (SSCD: {int(dups.flag_sscd.sum()) if len(dups) else 0}, "
        f"pHash: {int(dups.flag_phash.sum()) if len(dups) else 0}, both: {int((dups.flag_sscd & dups.flag_phash).sum()) if len(dups) else 0}); "
        f"distinct images involved: {len(dup_ids)}",
    ]
    if len(dups):
        tiers = {t: int((dups.sscd_sim >= t).sum()) for t in (0.6, 0.75, 0.9)}
        ex = dups.exact_duplicate
        lines += [
            f"- SSCD tiers (pairs with sim >= t): {tiers}",
            f"- Byte-identical train/test files: {int(ex.sum())}, of which with DIFFERENT official fine labels: "
            f"{int((ex & dups.label_conflict).sum())} (label noise in the official annotations)",
            f"- Label conflicts among all candidate pairs: {int(dups.label_conflict.sum())}",
        ]
    sha_groups = meta.groupby("raw_sha256").agg(n=("id", "count"), splits=("official_split", lambda s: "+".join(sorted(set(s)))),
                                                n_fine=("fine_id", "nunique"))
    within = sha_groups[(sha_groups.n > 1) & ~sha_groups.splits.str.contains(r"\+")]
    lines.append(f"- Byte-identical groups within one official split: {len(within)} "
                 f"({int((within.n_fine > 1).sum())} with conflicting fine labels)")
    if "label_conflict" in meta:
        lines.append(f"- Label-conflict images (byte-identical, different fine labels): {int(meta.label_conflict.sum())}; "
                     f"excluded from test-side evaluation and episodes (`data/splits/eval_exclude.txt`): {int(meta.eval_exclude.sum())}")
    if "n_near_duplicates_within_test" in meta:
        lines.append(f"- Test images with a near-duplicate inside test: {int((meta.n_near_duplicates_within_test > 0).sum())} "
                     f"(`data/duplicates_within_test.csv`; episodes avoid such pairs across S and T)")
    if nn_summary is not None:
        qs = nn_summary.sscd_nn_sim.quantile([0.5, 0.9, 0.99, 0.999]).round(3).tolist()
        lines.append(f"- Test->train SSCD nearest-neighbour similarity, quantiles 50/90/99/99.9%: {qs} "
                     f"(this is the null for G7)")
    if len(dups):
        lines += ["", dups.head(30).to_markdown(index=False)]
    lines += ["", "## Per make", "", per_make.to_markdown(), "",
              "Per fine class: `reports/images_per_fine_class.csv`.", ""]
    (out_dir / "data_summary.md").write_text("\n".join(lines))
